services:
  test:
    extends:
      file: tools/compose.yml
      service: dummy
    container_name: test1
    volumes:
      - ./run.sh:/run.sh
    command: ["/run.sh"]

  test2:
    extends: test
    container_name: test2