#linux/amd64
version: "3.9"
services:
  mosquitto:
    image: mosquitto:f438899_20240922
    build:
      dockerfile_inline: FROM eclipse-mosquitto@sha256:f43889926d948c1146751bce701373b71c16a81e5de9b2986b7589221fa4d9e9
    container_name: mosquitto
    #security_opt:
     # - no-new-privileges:true
    restart: always
    ports: 
      - 1883:1883
      - 9001:9001
    volumes:
      - ./volume1/docker/mosquitto/config:/mosquitto/config
      - ./volume1/docker/mosquitto/data:/mosquitto/data
      - ./volume1/docker/mosquitto/log:/mosquitto/log
    environment:
      - TZ=Europe/Paris

  alt:
    image: eclipse-mosquitto:custom-tag@sha256:f43889926d948c1146751bce701373b71c16a81e5de9b2986b7589221fa4d9e9