services:
  # Exposes docker.sock to port 2375
  prep:
    image: alpine/socat
    container_name: test-build-prep
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 2375:2375
    command: tcp-listen:2375,reuseaddr,fork unix-connect:/var/run/docker.sock

  workaround:
    image: deanayalon/tests:build-sock-workaround
    build: 
      dockerfile: dockerfile.workaround

  additional:
    image: deanayalon/tests:build-sock
    build:
      dockerfile: dockerfile.context
      additional_contexts:
        - run=/var/run