services:
  mosquitto:
    image: eclipse-mosquitto@sha256:d12c8f80dfc65b768bb9acecc7ef182b976f71fb681640b66358e5e0cf94e9e9
    container_name: mosquitto
    #security_opt:
    # - no-new-privileges:true
    restart: always
    ports:
    - 1883:1883
    - 9001:9001
    volumes:
    - /volume1/docker/mosquitto/config:/mosquitto/config
    - /volume1/docker/mosquitto/data:/mosquitto/data
    - /volume1/docker/mosquitto/log:/mosquitto/log
    environment:
    - TZ=Europe/Paris